name: Create or Update Lambda Function

on:
  workflow_dispatch:
    inputs:
      lambdaFunctionName:
        description: 'Lambda Function Name'
        required: true
        default: 'newsubs'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Get latest image tag from ECR
      id: get-latest-tag
      run: |
        LATEST_TAG=$(aws ecr describe-images \
          --repository-name ${{ secrets.AWS_ECR_REGISTRY }} \
          --region $AWS_REGION \
          --output json \
          | jq -r '.imageDetails | sort_by(.imagePushedAt) | last | .imageTags[]' \
          | grep -v latest)
        echo "Latest tag: $LATEST_TAG"
        echo "::set-output name=tag::$LATEST_TAG"

    - name: Create or Update Lambda Function
      run: |
        aws lambda create-function --function-name ${{ github.event.inputs.lambdaFunctionName }} \
        --package-type Image \
        --code ImageUri=${{ secrets.AWS_ECR_REGISTRY }}/newsubs:${{ steps.get-latest-tag.outputs.tag }} \
        --role arn:aws:iam::849441246713:role/lambda_full
      continue-on-error: true

    - name: Update Lambda Function Code
      if: ${{ steps.deploy-lambda.outcome == 'failure' }}
      run: |
        aws lambda update-function-code --function-name ${{ github.event.inputs.lambdaFunctionName }} \
        --image-uri ${{ secrets.AWS_ECR_REGISTRY }}/newsubs:${{ steps.get-latest-tag.outputs.tag }}
